[package]
name = "basic"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
slung = { path = "../.." }
slung-macros = { path = "../../macros" }

[lints.rust]
dead_code = "allow"

[profile.release]
opt-level = "z"
lto = true

[profile.dev]
opt-level = 1

[workspace]
